steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    verbose: false
    condition: succeeded() # Run this task only if previous tasks succeeded
    continueOnError: false # Stop the pipeline if this task fails; subsequent tasks will not be executed  
    enabled: true  # Set to false to disable this task